### ISSUE TITLE
Web is not working with "www." prefix

### ISSUE THREAD

**Issue by radeczek** [jakubgarfield/chodounsky.net#2]
Hi,
in Bonobo.Git.Server you are using address for chodounsky.net with "www." prefix which is not working. Can you fix it?
Thanx.
Rcz

**Comment by jakubgarfield** [comment]
Thanks for letting me know, my websites broke after migration to Azure. If you ever do it, don't forget to put www.something.com to you azure domain and awverify.www as a CNAME.
